#pragma acr monitor (data[2][i][j], min, monfiltre)
#pragma acr monitor (bis[2][25][15], max)
#pragma acr monitor (bis[2]25][15], max)
#pragma acr monitor (data[2][i][j], randomfunction)
#pragma acr monitor (bis[2][25][15], min)
