#!/bin/bash

if [ $# -ne 2 ]
then
  echo "Usage : $0 <new_grid_size> <filename>"
  exit 1
fi

sed -i.bak -e "s/\(#pragma[[:space:]]*acr[[:space:]]*grid\([[:space:]]\)*(\)\([[:digit:]]*\))/\1$1)/g" $2
