/*
 * Copyright (C) 2016 Maxime Schmitt
 *
 * ACR is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

#include "acr/gencode.h"

#include <string.h>

#include "acr/acr_openscop.h"
#include "acr/print.h"
#include "acr/utils.h"

int start_acr_parsing(FILE* file, acr_compute_node* node_to_init);

void acr_generate_code(const char* filename) {
  FILE* current_file = fopen(filename, "r");
  if (current_file == NULL) {
    fprintf(stderr, "Unable to open file: %s\n", filename);
    perror("fopen");
    return;
  }

  acr_compute_node compute_node = NULL;
  start_acr_parsing(current_file, &compute_node);

  if (compute_node == NULL) {
    fprintf(stderr, "No pragma ACR found in file: %s\n", filename);
    return;
  }
  acr_compute_node all_options = acr_copy_compute_node(compute_node);
  acr_compute_node_list node_list =
    acr_new_compute_node_list_split_node(compute_node);

  if (node_list) {
    const unsigned long list_size = acr_compute_node_list_get_size(node_list);
    for (unsigned long i = 0; i < list_size; ++i) {
        acr_compute_node node = acr_compute_node_list_get_node(i, node_list);
        osl_scop_p scop = acr_extract_scop_in_compute_node(
            node, current_file, filename);
        if (scop) {
          if (scop->next) {
            osl_scop_free(scop->next);
            scop->next = NULL;
          }
          size_t name_size = strlen(filename);
          char* new_file_name = malloc(name_size + 5 * sizeof(*new_file_name));
          strcpy(new_file_name, filename);
          new_file_name[name_size] = '-';
          new_file_name[name_size + 1] = 'a';
          new_file_name[name_size + 2] = 'c';
          new_file_name[name_size + 3] = 'r';
          new_file_name[name_size + 4] = '\0';
          FILE* new_file = fopen(new_file_name, "w");
          if (!new_file) {
            perror("fopen");
            continue;
          }
          acr_generate_preamble(new_file, filename);
          free(new_file_name);
          fclose(new_file);
        }
    }
  }

  acr_free_compute_node(all_options);
  /*
  char* buffer = NULL;
  size_t sizebuffer;
  acr_print_scop_to_buffer(scop, &buffer, &sizebuffer);
  fprintf(stderr, "%s", buffer);
  osl_scop_free(scop);
  scop = acr_read_scop_from_buffer(buffer, sizebuffer);
  osl_scop_print(stderr, scop);
  osl_scop_free(scop);
  free(buffer);
  */
}

void acr_generate_preamble(FILE* file, const char* filename) {
  fprintf(file,
      " /*\n"
      "   File automatically generated by ACR from input file named %s\n"
      "   Please do not read this line.\n"
      "   Seriously why did you read it?\n"
      " */\n", filename);
      // # include here
}

void acr_print_structure_and_related_scop(FILE* out, const char* filename) {
  FILE* current_file = fopen(filename, "r");
  if (current_file == NULL) {
    fprintf(stderr, "Unable to open file: %s\n", filename);
    perror("fopen");
    return;
  }

  acr_compute_node compute_node = NULL;
  start_acr_parsing(current_file, &compute_node);

  if (compute_node == NULL) {
    fprintf(out, "No pragma ACR found in file: %s\n", filename);
  } else {

    acr_compute_node_list node_list =
      acr_new_compute_node_list_split_node(compute_node);
    if (node_list) {
      for(unsigned long j = 0; j < node_list->list_size; ++j) {
        acr_compute_node node = acr_compute_node_list_get_node(j, node_list);
        osl_scop_p scop = acr_extract_scop_in_compute_node(
            node, current_file, filename);
        if (scop) {
          if (scop->next) {
            osl_scop_free(scop->next);
            scop->next = NULL;
          }
          fprintf(out, "##### ACR options for node %lu: #####\n", j);
          pprint_acr_compute_node(out, node, 0ul);
          fprintf(out, "##### Scop for node %lu: #####\n", j);
          osl_scop_print(out, scop);
          osl_scop_free(scop);
        } else {
          fprintf(out, "##### No scop found for node %lu: #####", j);
          pprint_acr_compute_node(out, node, 0ul);
        }
        fprintf(out, "\n");
      }
    } else {
      fprintf(out, "No ACR node has been found in file: %s\n", filename);
    }
    acr_free_compute_node_list(node_list);
  }
  fclose(current_file);
}
